export const data = [
  {
    id: 1,
    name: 'Saksham Bhutani',
    img: 'https://source.unsplash.com/random',
    title: 'President',
    line: 'Lmao',
    insta: 'www.instagram.com',
    linkedin: 'www.linkedin.com',
  },
  {
    id: 2,
    name: 'Saksham Bhutani',
    img: 'https://source.unsplash.com/random',
    title: 'President',
    line: 'Lmao',
    insta: 'www.instagram.com',
    linkedin: 'www.linkedin.com',
  },
  {
    id: 3,
    name: 'Saksham Bhutani',
    img: 'https://source.unsplash.com/random',
    title: 'President',
    line: 'Lmao',
    insta: 'www.instagram.com',
    linkedin: 'www.linkedin.com',
  },
  {
    id: 4,
    name: 'Saksham Bhutani',
    img: 'https://source.unsplash.com/random',
    title: 'President',
    line: 'Lmao',
    insta: 'www.instagram.com',
    linkedin: 'www.linkedin.com',
  },
  {
    id: 5,
    name: 'Saksham Bhutani',
    img: 'https://source.unsplash.com/random',
    title: 'President',
    line: 'Lmao',
    insta: 'www.instagram.com',
    linkedin: 'www.linkedin.com',
  },
];
