export const data = [
  {
    id: 1,
    name: 'Saksham Bhutani',
    img: 'https://i.imgur.com/YP7FQy3.jpg',
    title: 'President',
    line: 'Lmao',
    insta: 'www.instagram.com',
    linkedin: 'https://www.linkedin.com/in/saksham-bhutani5',
  },
  {
    id: 2,
    name: 'Ayush kataria',
    img: 'https://i.imgur.com/K3JLIzf.jpg',
    title: 'Vice President - Project Administration',
    line: 'Lmao',
    insta: 'www.instagram.com',
    linkedin: 'https://www.linkedin.com/in/ayush-kataria-439803193',
  },
  {
    id: 3,
    name: 'Abhiluv Anand',
    img: 'https://i.imgur.com/tXL7t94.jpg',
    title: 'Vice President - Operations and Finance',
    line: 'Lmao',
    insta: 'www.instagram.com',
    linkedin: 'https://www.linkedin.com/in/abhiluv-anand',
  },
  {
    id: 4,
    name: 'Yash Gupta',
    img: 'https://i.imgur.com/r9YbLyZ.jpg',
    title: 'Project Head - Aarosh',
    line: 'Lmao',
    insta: 'www.instagram.com',
    linkedin: 'https://www.linkedin.com/in/yash-gupta-a41314197',
  },
  {
    id: 5,
    name: 'Ruchir Kain',
    img: 'https://i.imgur.com/E3FC18Y.jpg',
    title: 'Project Head - Aarosh',
    line: 'Lmao',
    insta: 'www.instagram.com',
    linkedin: 'https://www.linkedin.com/in/ruchir-kain-732583186',
  },
  {
    id: 6,
    name: 'Tashvik Dhamija',
    img: 'https://i.imgur.com/DJ1VzJe.jpg',
    title: 'Project Head - Milan',
    line: 'Lmao',
    insta: 'www.instagram.com',
    linkedin: 'https://www.linkedin.com/in/tashvikdhamija',
  },
  {
    id: 7,
    name: 'Vanishka Kadian',
    img: 'https://source.unsplash.com/random',
    title: 'Project Head - Swajal',
    line: 'Lmao',
    insta: 'www.instagram.com',
    linkedin: 'https://www.linkedin.com/in/vanishka-kadian',
  },
  {
    id: 8,
    name: 'Ishan Prakash',
    img: 'https://i.imgur.com/SMQ7yXc.jpg',
    title: 'Project Head - Unnati',
    line: 'Lmao',
    insta: 'www.instagram.com',
    linkedin: 'www.linkedin.com',
  },
  {
    id: 9,
    name: 'Karan',
    img: 'https://source.unsplash.com/random',
    title: 'Marketing Head',
    line: 'Lmao',
    insta: 'www.instagram.com',
    linkedin: 'https://www.linkedin.com/in/karan16bhardwaj',
  },
  {
    id: 10,
    name: 'Vibhor',
    img: 'https://i.imgur.com/DzqhgCy.jpg',
    title: 'Marketing Head',
    line: 'Lmao',
    insta: 'www.instagram.com',
    linkedin: 'https://www.linkedin.com/in/vibhor-gautam-2839a2196',
  },
  {
    id: 11,
    name: 'Archit Agarwal',
    img: 'https://i.imgur.com/FHrCM91.jpg',
    title: 'Research Head',
    line: 'Lmao',
    insta: 'www.instagram.com',
    linkedin: 'https://www.linkedin.com/in/archit-agarwal30',
  },
  {
    id: 12,
    name: 'Arushi Singh',
    img: 'https://i.imgur.com/E7BYlNx.jpg',
    title: 'Research Head',
    line: 'Lmao',
    insta: 'www.instagram.com',
    linkedin: 'https://www.linkedin.com/in/arushi-singh-6a53221a0',
  },

  {
    id: 13,
    name: 'Krishna Kedia',
    img: 'https://i.imgur.com/smWEGwg.jpg',
    title: 'Technical Head',
    line: 'Lmao',
    insta: 'www.instagram.com',
    linkedin: 'https://www.linkedin.com/in/krishna-kedia-39b87a134',
  },
  {
    id: 14,
    name: 'Preeti Bhansali',
    img: 'https://i.imgur.com/61Ala3D.jpg',
    title: 'East Campus Head',
    line: 'Lmao',
    insta: 'www.instagram.com',
    linkedin: 'https://www.linkedin.com/in/preetibhansali',
  },
];
